#!/bin/bash
gcc -S -masm=intel $CFILE\
#include<stdio.H>
#include<unistd.h>

/**
*main -prints a quote
*
Return: Always 0 (success)
*/
int main(void)
{
write(2,"and that piece of art is usefull\"-Dora korp,2015-10-19\n",59);
return (1);
